repositories:
 - name: example
   url: https://github.com/helm/examples.git

releases:
- name: prom-norbac-ubuntu
  namespace: om
  chart: charts/hello-world
  set:
  - name: rbac.create
    value: false
