repositories:
 - name: helm-repo
   url: https://prometheus-community.github.io/helm-charts

releases:
- name: prom-norbac-ubuntu
  namespace: om
  chart: prometheus-community/prometheus
  set:
  - name: rbac.create
  values:
    - ./values/override.yaml.gotmpl
