repositories:
 - name: hello-world
   url: https://github.com/akashpawar007/hello-world.git

releases:
- name: hello-world
  namespace: om
  chart: hello-world-chart
  set:
  - name: rbac.create
    value: false
