repositories:
 - name: nginx
   url: https://github.com/techiescamp/helm-tutorial.git

releases:
- name: prom-norbac-ubuntu
  namespace: om
  chart: nginx-chart
  set:
  - name: rbac.create
    value: false
